apiVersion: v2
name: orchestrator-k8s
description: |
  Helm chart to deploy the Orchestrator solution suite on Kubernetes, including Janus IDP backstage, SonataFlow Operator, Knative Eventing and Knative Serving.
type: application
version: 0.2.0
appVersion: "0.0.1"

dependencies:
  - name: backstage
    repository: https://janus-idp.github.io/helm-backstage
    version: "2.11.4"
  - name: postgresql-persistent
    repository: https://sclorg.github.io/helm-charts
    version: "0.0.3"
    condition: postgresql-persistent.enabled
  - name: serverless-knative
    repository: "file://charts/serverless-knative"
    version: "0.1.0"
    condition: serverless-knative.enabled
  - name: sonataflow-operator
    repository: "file://charts/sonataflow-operator"
    version: "0.1.2"
    condition: sonataflow-operator.enabled
  - name: workflows
    repository: https://parodos.dev/serverless-workflows-helm
    version: "0.2.0"
    condition: workflows.enabled

icon: https://raw.githubusercontent.com/parodos-dev/parodos-dev.github.io/main/assets/images/WO_black.svg

