appName: orchestrator

global:
  host: localhost # Specify your own Ingress host

sonataflow-operator:
  enabled: true

serverless-knative:
  enabled: true

workflows:
  enabled: true

serviceAccountName: orchestrator-sa

labels:
  - app: orchestartor 

postgresql-persistent:
  # depends on sonataflow-operator which still uses the ephemeral image. 
  enabled: false
  database_service_name: workflows-db
  memory_limit: 512Mi
  volume_capacity: 1Gi
  config:
    postgresql_database: testdb
    postgresql_password: testp
    postgresql_user: testu
    port: 5432
  image:
    tag: "latest"

# override Janus image with one with the orchestrator plugin
# May change with dynamic plugin support
backstage: 
  route:
    # set to false for kubernetes
    enabled: false
  global:
    dynamic:
      includes:
      - dynamic-plugins.default.yaml
      plugins:
      - disabled: false
        integrity: sha512-4BsB2jdgzBNYpE0IcFYmlEgfu6HJnD9uX8ZpzzYHTkMs8AU3aWWb3PZG0nu/y5s8m0kr4TBbS++gePwRdqDrgw==
        package: '@janus-idp/backstage-plugin-orchestrator-backend-dynamic@0.0.1'
        pluginConfig:
          orchestrator:
            dataIndexService:
              url: http://sonataflow-platform-data-index-service
            editor:
              path: https://sandbox.kie.org/swf-chrome-extension/0.32.0
      - disabled: false
        integrity: sha512-QYwZ5MTckS1gQQIQUBoOboiGefCtkcG+S8IFPiJ+6rPEtjzmUpVL5TmG1hXCUHWBMJP/+tKxlpNQib2SMInRnA==
        package: '@janus-idp/backstage-plugin-orchestrator@1.0.0'
        pluginConfig:
          dynamicPlugins:
            frontend:
              janus-idp.backstage-plugin-orchestrator:
                appIcons:
                - importName: OrchestratorIcon
                  module: OrchestratorPlugin
                  name: orchestratorIcon
                dynamicRoutes:
                - importName: OrchestratorPage
                  menuItem:
                    icon: orchestratorIcon
                    text: Orchestrator
                  module: OrchestratorPlugin
                  path: /orchestrator
  upstream:
    ingress:
      enabled: true  # Use Kubernetes Ingress instead of OpenShift Route
    backstage:
      resources:
        limits:
          memory: 2Gi
          cpu: 1000m
        requests:
          memory: 800Mi
          cpu: 200m
      
      podSecurityContext:  # Vanilla Kubernetes doesn't feature OpenShift default SCCs with dynamic UIDs, adjust accordingly to the deployed image
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001

    backstage:
      image:
        tag: next
      appConfig:
        app:
          baseUrl: http://localhost:9090
        backend:
          baseUrl: http://localhost:9090
          cors:
            origin: http://localhost:9090
        integrations:
          github:
            - host: github.com
              token: "INSERT VALID TOKEN HERE"
        auth:
          environment: development
          providers:
            github:
              development:
                clientId: "INSERT VALID CLIENT ID HERE"
                clientSecret: "INSERT VALID CLIENT SECRET HERE"
        catalog:
          rules:
            - allow:
                [
                  Component,
                  System,
                  Group,
                  Resource,
                  Location,
                  Template,
                  API,
                  User,
                  Domain,
                ]
          locations:
            - type: url
              target: https://github.com/parodos-dev/workflow-software-templates/blob/main/entities/workflow-resources.yaml
            - type: url
              target: https://github.com/parodos-dev/workflow-software-templates/blob/main/template/template.yaml
            - type: url
              target: https://github.com/janus-idp/software-templates/blob/main/showcase-templates.yaml
          csp:
            frame-src:
              - "https://sandbox.kie.org"
        orchestrator:
          catalog:
            environment: development

          
